- name: install basic tools
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items:
    - bc
    - bmon
    - chromium
    - htop
    - glances
    - iotop
    - iptstate
    - keepass2
    - multitail
    - mtr
    - nethogs
    - nmon
    - peco
    - powertop
    - seafile-cli
    - seafile-gui
    - thunderbird
    - tmux
  become: yes
