- name: install git
  package:
    name: git
    state: latest
    use: apt
  become: yes

- name: clone dotfiles repo
  git:
    repo: "https://github.com/xpac1985/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/dotfiles"

- name: chmod setup.sh
  file:
    path: "{{ ansible_env.HOME }}/dotfiles/setup.sh"
    mode: "+x"

- name: execute setup.sh
  shell: "{{ ansible_env.HOME }}/dotfiles/setup.sh"

