- name: download Sublime3 repo key
  get_url:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    dest: "/tmp/sublimehq-pub.gpg"
  register: key_download

- name: "add Sublime3 repo key to apt"
  shell: "apt-key add /tmp/sublimehq-pub.gpg"
  when: key_download.changed
  become: yes
  register: key_import

- name: delete Sublime3 repo key file
  file:
    path: /tmp/sublimehq-pub.gpg
    state: absent
  when: key_import.changed

- name: copy apt sources list file
  copy:
    src: "{{ role_path }}/files/sublime-text.list"
    dest: "/etc/apt/sources.list.d/sublime-text.list"
    owner: root
    group: root
    mode: 0644
  become: yes
  when: key_import.changed

- name: install Sublime3 from repo
  apt:
    name: sublime-text
    update_cache: yes
  become: yes
  when: key_import.changed
